name: Auto Deploy on Merge

on:
  push:
    branches:
      - main  # Trigger on merges to the main branch
    # You can use the "types" field to limit this to merges
    types:
      - merged

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up SSH keys to connect to your server
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H your_server_ip >> ~/.ssh/known_hosts

      # Step 3: Deploy the changes
      - name: Deploy to server
        run: |
          ssh user@your_server_ip << 'EOF'
            cd /var/www/RouteX || exit
            git pull origin main  # Pull the latest changes from the repository
            sudo systemctl restart nginx  # Restart Nginx to apply the changes
          EOF
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
