name: Auto Deploy WordPress on Merge or Push to Main

on:
  push:
    branches:
      - main  # Trigger on pushing to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code from the Repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up SSH with Private Key
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa  # Use your private key stored in GitHub Secrets
          chmod 600 ~/.ssh/id_rsa
          echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

      # Step 3: Get Latest Commit Hash and Update wp-config.php
      - name: Update GITHUB_DEPLOYMENT_SLUG in wp-config.php
        run: |
          VERSION=$(git rev-parse --short HEAD)  # Get short version of the commit hash
          echo "Setting GITHUB_DEPLOYMENT_SLUG to $VERSION"
          ssh -i ~/.ssh/id_rsa root@${{ secrets.SERVER_IP }} << EOF
            cd /var/www/routex || exit  # Change to your WordPress directory
            # Update the slug in wp-config.php, replacing any existing value
            sed -i "s/define('GITHUB_DEPLOYMENT_SLUG', '[^']*');/define('GITHUB_DEPLOYMENT_SLUG', '${VERSION}');/" wp-config.php
          EOF

      # Step 4: Pull Latest Changes and Deploy to the Server
      - name: Deploy to Server
        run: |
          ssh -i ~/.ssh/id_rsa root@${{ secrets.SERVER_IP }} << EOF
            cd /var/www/routex || exit  # Change to your WordPress directory
            git pull origin main  # Pull the latest changes from the GitHub repository
            # Optionally flush the cache if FLUSH_CACHE is set to true
            if [ "${{ secrets.FLUSH_CACHE }}" == "true" ]; then
              wp cache flush  # Clear the cache (if using a WordPress caching plugin)
              echo "Cache has been flushed."
            fi
            # Restart Nginx to apply any configuration changes
            sudo systemctl restart nginx
          EOF

      # Optional Step 5: Push Changes Back to GitHub (only if necessary)
      - name: Push Changes Back to GitHub (optional)
        if: github.event.head_commit.message == 'manual commit'
        run: |
          ssh -i ~/.ssh/id_rsa root@${{ secrets.SERVER_IP }} << EOF
            cd /var/www/routex || exit  # Change to your WordPress directory
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"
            git add .  # Stage all changes made to the server
            git commit -m "Automated commit from server changes" || echo "No changes to commit"
            git push origin main  # Push changes to GitHub if necessary
          EOF
