name: Auto Deploy on Merge

on:
  push:
    branches:
      - main 
    types:
      - merged

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 23.88.98.228 >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh root@23.88.98.228 << 'EOF'
            cd /var/www/RouteX || exit
            git pull origin main  # Pull the latest changes from the repository
            sudo systemctl restart nginx  # Restart Nginx to apply the changes
          EOF
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
