name: Deploy to WordPress

on:
  push:
    branches:
      - main  # Change to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H your-server-ip >> ~/.ssh/known_hosts

    - name: Deploy to server
      run: |
        rsync -avz --delete ./wordpress/ your-username@your-server-ip:/var/www/wordpress
