name: Update WordPress Version

on:
  push:
    branches:
      - main

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up SSH with private key
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo -e "Host ${{ secrets.SERVER_IP }}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

- name: Update Version in wp-config.php
        run: |
    set -e
    VERSION=$(git rev-parse --short HEAD)
    echo "Setting GITHUB_DEPLOYMENT_SLUG to $VERSION"
    ssh -v -i ~/.ssh/id_rsa root@${{ secrets.SERVER_IP }} << 'EOF'
      set -x
      cd /var/www/RouteX || exit
      grep "GITHUB_DEPLOYMENT_SLUG" wp-config.php || echo "No matching lines found"
      sed -i "s/define( 'GITHUB_DEPLOYMENT_SLUG', .*/define( 'GITHUB_DEPLOYMENT_SLUG', '$VERSION' );/" wp-config.php
      grep "GITHUB_DEPLOYMENT_SLUG" wp-config.php
    EOF
